
name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ministryofjustice/setup-git-crypt@main

      - name: Write git-crypt key to file
        run: |
          echo ${{ secrets.GIT_CRYPT_KEY }} > .git-crypt-key

      - name: Unlock encrypted files
        run: |
          github-bin/git-crypt unlock ./.git-crypt-key

      - name: Check hash
        run: |
          cat ./src/Helpers/verified-quiz/quiz.ts | md5sum


      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.DOKKU_SSH_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PK}}
